### ISSUE TITLE
Check for same existing version

### ISSUE THREAD

**Issue by midweste** [linuxmint/mintupgrade#20]
Was upgrading a few installations and one already had LMDE 5.  Nearly went all the way through the update before I realized i was "upgrading" to the same version.  May be a good idea to put a check in to see if the user is already using LMDE 5

**Comment by clefebvre** [comment]
In theory yes. In practice the tool was designed to go step by step in a reproducible way so that it doesn't matter how many times you run it, whether it stops in the meantime or not, and how far you went in the upgrade. This means it needs to work both when you're still on the previous release and both when you're already pointing to the new one.
